#!/bin/sh
. "$(dirname "$0")/_/husky.sh"


"./$(dirname "$0")/check_branch_name.sh"
yarn workspace application format:staged
yarn workspace landing format:staged
# yarn workspace application lint
# yarn workspace landing lint